### ISSUE TITLE
Strange installation script

### ISSUE THREAD

**Issue by tshipenchko** [FoxUserbot/FoxUserbot#1]
Why is there no requirements.txt? It's de-facto standard for requirements in python3

Your install.sh doesn't install the colorama, which is needed from running of install.py (https://github.com/FoxUserbot/FoxUserbot/blob/33123a082b5cb2b458a77457445c8c683fdeb781/install.py#L2)
Moreover, why you install git, despite you don't use it in installation, which is better than using zip. If you really don't wish to use git, use zip directly via standard linux input: https://askubuntu.com/questions/653505/uncompress-file-from-url-to-hard-disk

```
>>> import os
>>> os.system("really_random_command")
sh: 1: really_random_command: not found
32512
```
There is no mean in try-except (https://github.com/FoxUserbot/FoxUserbot/blob/33123a082b5cb2b458a77457445c8c683fdeb781/install.py#L18)

**Comment by veselcraft** [comment]
> There is no mean in try-except

**Comment by veselcraft** [comment]
He tried to automatically install everything that is needed
```python
requirements = ["pyrogram", "requests", "wget", "telegraph"]
for rq in requirements:
    os.system(f"pip3 install -U {rq}")```
But nah, this is stupid
> Your install.sh doesn't install the colorama, which is needed from running of install.py
That's why `requirements.txt` is required.

> There is no mean in try-except
I think he tried to run main.py in another process. Otherwise, he can just do this:
```python
os.system(sys.executable + " main.py")
```

I'm not really python developer, but it's incorrect in my opinion

**Comment by tshipenchko** [comment]
I see, he tried to automatically install everything, but it's recommended to use requirements.txt. Along-with, using pip together with os.system isn't the best way.
That would be better:
```
import pip
pip.main(["install", "telegraph", "pyrogram", "--upgrade"])
``` 

I think, completely rewrite of the installation script is needed.

**Comment by A9FM** [comment]
Thank for helping, i edit install.py and install.sh

**Comment by terexdev** [comment]
ебать сколько тут людей пздц

**Comment by veselcraft** [comment]
@A9FM Close the issue if it's will be resolved

алсо здарова из эхобота
