### ISSUE TITLE
Complete non-compliance with PEP8 standards

### ISSUE THREAD

**Issue by tshipenchko** [FoxUserbot/FoxUserbot#2]
Whole your code is burning like a Christmas tree in the IDE
![image](https://user-images.githubusercontent.com/52406854/150723806-c043f429-ddee-424a-abb7-7ac18e52095e.png)

**Comment by terexdev** [comment]
@A9FM срочно!

**Comment by A9FM** [comment]
Сейчас буду фиксить, ожидай

**Comment by gh0stc0der1** [comment]
Thanks for the help with the userbot! Would you like to join our team? We see you are experienced. How to contact you?

**Comment by gh0stc0der1** [comment]
Thanks for the help with the userbot! Do you want to join our team? We see that you are experienced. If you agree, please write to our SUPPORT bot. We will give you a link to the group. @foxsupportedrobot 

~Gh0st.

**Comment by A9FM** [comment]
Fixed! I refactor the code
